# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(choices=[('XF', 'England'), ('XI', 'Wales'), ('NI', 'NI'), ('XH', 'Scotland')], default='XF', max_length=2)),
                ('PUBUKPRN', models.IntegerField(validators=[front.models.validate_pubukprn])),
                ('APROutcome', models.CharField(max_length=255)),
                ('TEFOutcome', models.CharField(max_length=255)),
            ],
        ),
    ]
