# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-20 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import front.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university_name', models.CharField(max_length=255)),
                ('Country', models.CharField(choices=[('UK', 'United Kingdom'), ('US', 'United States')], default='US', max_length=2)),
                ('num_students', models.IntegerField(validators=[front.models.validate_students])),
                ('description', models.TextField()),
                ('tuition', models.IntegerField()),
            ],
        ),
    ]
