# Generated by Django 2.1.7 on 2019-03-19 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='Name',
            field=models.CharField(default='uni', max_length=255),
            preserve_default=False,
        ),
    ]
